language: python
python:
- "2.7"
- "3.6"
- pytest
- pytest-cov
install:
- pip install pytest
- pip install pytest-cov
# command to run tests
script:
- pytest --cov=src # or py.test for Python versions 3.5 and below
